In [1]:
import numpy as np

### Drawbacks of Broadcasting

Sometimes, when you perform broadcastng it can introduce very subtle or strange looking bugs, if you are not familiar with all of the intricacies of how broadcasting and how features like broadcasting works. For example, if you add a column vector with a row vector, you may be expecting that it returns an error stating the mismatch of dimensions but what you might actually get is the sum of both the vectors. Below is the code that creates 5 random Gaussian variables stored in an array

In [2]:
a = np.random.randn(5)

In [6]:
print(a)

[ 0.62305804  0.40607103 -1.22784989 -0.52965204  0.40489927]


In [4]:
print(a.shape)

(5,)


The above structure is rank 1 array, meaning array with 1 dimension, and is neither a column vector or a row vector. This leads to some undesirable behavior. Firstly, a.T doesn't result in anything and the array is returned as it is:

In [5]:
print(a.T)

[ 0.62305804  0.40607103 -1.22784989 -0.52965204  0.40489927]


Secondly, if you take the dot product of the same array, it returns back a number instead of a another matrix

In [7]:
print(np.dot(a, a.T))

2.5051850543863514


So, when working with NN, you should never work with rank 1 arrays, if you want to define a column vector or a row vector, you can do so as follows:

In [8]:
col_vec = np.random.randn(5, 1)
row_vec = np.random.randn(1, 5)

In [9]:
print(col_vec)

[[ 0.48026196]
 [-1.26194703]
 [ 0.99689234]
 [-1.36185452]
 [ 0.71736028]]


In [10]:
print(row_vec)

[[ 0.75996523  1.22697821 -0.09173272  0.11574996 -0.98203865]]


In [11]:
print(np.dot(col_vec, col_vec.T)) # now gives you a matrix

[[ 0.23065155 -0.60606515  0.47876947 -0.65404692  0.34452085]
 [-0.60606515  1.59251031 -1.25802534  1.71858827 -0.90527068]
 [ 0.47876947 -1.25802534  0.99379435 -1.35762235  0.71513098]
 [-0.65404692  1.71858827 -1.35762235  1.85464774 -0.97694035]
 [ 0.34452085 -0.90527068  0.71513098 -0.97694035  0.51460578]]
